Reference service during runtime instead of storing in constructor
CoorpAcademy/serverless-plugins pull request #121
Opened 2020-03-25 10:02 UTC by nzchicken

There is a slight weirdness with serverless, in that during the init hook, `this.serverless.service` isn't always compiled when refering to resources that might live in a different file. This means the resolution of the resource fails for getting streams. For example:

severless.yml
```
service:
  name: service

plugins:
  - serverless-offline-dynamodb-streams
  - serverless-offline

custom:
  serverless-offline:
    port: 3001
  serverless-offline-dynamodb-streams:
    apiVersion: '2013-12-02'
    endpoint: http://0.0.0.0:8000
    region: us-east-1
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false
    readInterval: 500

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1

functions:
  hello:
    handler: src/hello.handler
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - MyTable
              - Arn

resources:
  - ${file(resources/dynamodb.yml)}
```

resources.yml
```
Resources:
  MyTable:
    Type: "AWS::DynamoDB::Table"
    DeletionPolicy: Retain
    Properties:
      TableName: MyTable
      AttributeDefinitions:
        -
          AttributeName: id
          AttributeType: S
      KeySchema:
        -
          AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_IMAGE
```

This PR changes the references to a function which gets the latest version from the service.

This is also referenced in the serverless bug here: https://github.com/serverless/serverless/pull/3911

2020-03-25 10:08 UTC, nzchicken commented
Another example from where it does "unexpected" things: https://forum.serverless.com/t/serverless-plugin-resolving-variable-references/2233

2020-09-25 16:08 UTC, AdrieanKhisbe commented on packages/serverless-offline-dynamodb-streams/src/index.js
> +  service() {
Would be best to rely on some `get` getter so there is no usage to be modified
```suggestion
  get service() {
```

2020-09-25 16:14 UTC, AdrieanKhisbe requested changes
Would need also to be applied to new offline s3 plugin

2020-09-25 16:14 UTC, AdrieanKhisbe commented on packages/serverless-offline-dynamodb-streams/src/index.js
> +      omitBy(isUndefined, this.service().provider),
```suggestion
      omitBy(isUndefined, this.service),
      omitBy(isUndefined, this.service.provider),
```
and so on

2020-09-25 16:17 UTC, AdrieanKhisbe commented
@nzchicken Would you have some traces when it does occurs?
I''m surprised I never faced it, and no issue was raised about that before.
(Thinking that issues mentioned dating from 2017, might have been fixed at some point)

2021-06-15 13:59 UTC, b-n commented
I'm sorry, this was a long time ago and I just realised I still had this PR open. I can't remember the use case, so closing 👍

2021-06-15 13:59 UTC, closed without merging